baseURL = "https://fifth-generation.netlify.app/"
title = "Fifth Generation"
theme = "ananke"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[languages]
  [languages.de]
    weight = 1
    languageName = "Deutsch"
    title = "Fifth Generation"
    contentDir = "content/de"

  [languages.en]
    weight = 2
    languageName = "English"
    contentDir = "content/en"

  [languages.hr]
    weight = 3
    languageName = "Hrvatski"
    contentDir = "content/hr"

[params]
  ShowShareButtons = false
  ShowReadingTime = false
  ShowBreadCrumbs = true
  defaultTheme = "light"

  [params.cover]
    show = true
    image = "/images/shutterstock_hero.jpg"
    alt = "Fifth Generation – 5G Infrastruktur"
    caption = "Zukunft bauen mit 5G – Fifth Generation"
    linkFullImages = false

[menu]

  [[menu.main]]
    identifier = "fallback"
    name = "Menu"
    url = "/"
    weight = 1

  [[languages.de.menu.main]]
    name = "Startseite"
    url = "/de/"
    weight = 1

  [[languages.de.menu.main]]
    name = "Projekte"
    url = "/de/projects/"
    weight = 2

  [[languages.de.menu.main]]
    name = "Über uns"
    url = "/de/about/"
    weight = 3

  [[languages.de.menu.main]]
    name = "Kontakt"
    url = "/de/contact/"
    weight = 4

  [[languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 1

  [[languages.en.menu.main]]
    name = "Projects"
    url = "/en/projects/"
    weight = 2

  [[languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 3

  [[languages.en.menu.main]]
    name = "Contact"
    url = "/en/contact/"
    weight = 4

  [[languages.hr.menu.main]]
    name = "Početna"
    url = "/hr/"
    weight = 1

  [[languages.hr.menu.main]]
    name = "Projekti"
    url = "/hr/projects/"
    weight = 2

  [[languages.hr.menu.main]]
    name = "O nama"
    url = "/hr/about/"
    weight = 3

  [[languages.hr.menu.main]]
    name = "Kontakt"
    url = "/hr/contact/"
    weight = 4
